version: "3.8"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - $PWD:$PWD
    command: sleep infinity
    networks: ["monorepo-network"]
    ports:
      - "3000:3000"
    extra_hosts:
      - host.docker.internal:host-gateway

networks:
  monorepo-network:
    name: monorepo-network
